name: Joy Prakash Sain's weblog
description: 
meta_description: "Joy Prakash Sain's weblog"

aboutPage: true

paginate: 20
baseurl: /
domain_name: 'localhost'
google_analytics: 'UA-143355223-1'
disqus: true

comments:
  disqus:
    shortname            : "joy-space"

# Details for the RSS feed generator
url:            'localhost'
author:         'Joy Prakash Sain'
authorTwitter:  'jpsain'

permalink:       /:year/:title/

sass:
  style: expanded

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
